
import fs from 'fs';
import path from 'path';
import { put } from '@vercel/blob';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Load environment variables from the root .env file
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootEnvPath = path.resolve(__dirname, '../../.env');

dotenv.config({ path: rootEnvPath });

if (!process.env.BLOB_READ_WRITE_TOKEN) {
  console.error('❌ Error: BLOB_READ_WRITE_TOKEN is missing in .env file.');
  process.exit(1);
}

const PUBLIC_DIR = path.resolve(__dirname, '../public');
const OUTPUT_FILE = path.resolve(__dirname, '../src/data/blobAssets.ts');
const EXTENSIONS = ['.png', '.jpg', '.jpeg', '.webp', '.svg', '.gif'];

async function uploadImages() {
  if (!fs.existsSync(PUBLIC_DIR)) {
    console.error(`❌ Error: Public directory not found at ${PUBLIC_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(PUBLIC_DIR);
  const imageFiles = files.filter(file => EXTENSIONS.includes(path.extname(file).toLowerCase()));

  console.log(`🔍 Found ${imageFiles.length} images to upload...`);

  const assetMap = {};

  for (const file of imageFiles) {
    const filePath = path.join(PUBLIC_DIR, file);
    const fileContent = fs.readFileSync(filePath);

    try {
      console.log(`⬆️ Uploading ${file}...`);
      const blob = await put(file, fileContent, {
        access: 'public',
        token: process.env.BLOB_READ_WRITE_TOKEN,
        addRandomSuffix: false // Keep filenames clean if possible, or true if we want unique
      });

      console.log(`✅ Uploaded ${file} -> ${blob.url}`);
      assetMap[file] = blob.url;
    } catch (error) {
      console.error(`❌ Failed to upload ${file}:`, error);
    }
  }

  const fileContent = `// This file is auto-generated by scripts/upload-blob.js
// Do not edit manually

export const blobAssets: Record<string, string> = ${JSON.stringify(assetMap, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`\n🎉 Success! Asset map written to ${OUTPUT_FILE}`);
}

uploadImages();
